<?php
$data = array (
  21 => 
  array (
    'cat_id' => '21',
    'cat_name' => '电子锁',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '8',
    'level' => 0,
    'id' => '21',
    'name' => '电子锁',
  ),
  24 => 
  array (
    'cat_id' => '24',
    'cat_name' => '智能插排',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 0,
    'id' => '24',
    'name' => '智能插排',
  ),
  22 => 
  array (
    'cat_id' => '22',
    'cat_name' => '智能抽屉',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '22',
    'name' => '智能抽屉',
  ),
  53 => 
  array (
    'cat_id' => '53',
    'cat_name' => '包装',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '53',
    'name' => '包装',
  ),
);
?>